/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-05-04 04:48:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

//not necessary but will improve readability down the line.
//alternatively, I was thinking of making this into a function. 
boolean is_logged_in = false;
if (session.getAttribute("user_id") != null) {
	is_logged_in = true;
}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        header {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("        main {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        section {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("        .description {\r\n");
      out.write("		    max-width: 800px; /* Adjust the width as needed */\r\n");
      out.write("		    margin: 0 auto; /* Center the content horizontally */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#additionalButtons {\r\n");
      out.write("    		display: flex;\r\n");
      out.write("    		justify-content: center;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#additionalButtons button {\r\n");
      out.write("   		 	margin: 0 5px; /* Adjust as needed */\r\n");
      out.write("   			padding: 10px 20px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Welcome to BuyMe</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<header>\r\n");
      out.write("        <h1>Welcome to BuyMe - Your Online Auction System</h1>\r\n");
      out.write("    </header>\r\n");
      out.write("    ");
 if (!is_logged_in) { 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <main>\r\n");
      out.write("        <section>\r\n");
      out.write("		    <h2>Welcome to BuyMe - Your Ultimate Auction Destination</h2>\r\n");
      out.write("		    <div class=\"description\">\r\n");
      out.write("		        <p>BuyMe is your premier online auction system, revolutionizing the way you buy and sell goods. With a user-friendly interface and robust features, BuyMe empowers users to bid on a wide range of items, from electronics to collectibles, and everything in between. Whether you're a seasoned bidder or a first-time buyer, BuyMe provides a seamless experience, connecting buyers and sellers worldwide. Say goodbye to traditional shopping constraints and hello to endless possibilities with BuyMe, where every bid brings you closer to your desired treasures. Join us today and embark on an exciting journey of discovery and acquisition.</p>\r\n");
      out.write("		    </div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("        <section>\r\n");
      out.write("            <h2>Get Started</h2>\r\n");
      out.write("            <p>Explore the features of BuyMe:</p>\r\n");
      out.write("            <button onclick=\"window.location.href='browse_items.jsp'\">Browse Items</button>\r\n");
      out.write("            <button onclick=\"window.location.href='Login.jsp'\">Login</button>\r\n");
      out.write("            <button onclick=\"window.location.href='Login.jsp'\">Register</button>\r\n");
      out.write("\r\n");
      out.write("            <!-- Add more buttons for additional actions -->\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("	\r\n");
      out.write("	");
 } else { 
      out.write("\r\n");
      out.write("		<body>\r\n");
      out.write("    \r\n");
      out.write("    <main>\r\n");
      out.write("        <section>\r\n");
      out.write("            <h2>Welcome back, ");
 out.print(session.getAttribute("username")); 
      out.write("!</h2>\r\n");
      out.write("            <p>What would you like to do today?</p>\r\n");
      out.write("        </section>\r\n");
      out.write("         <section>\r\n");
      out.write("            <h2>Explore BuyMe</h2>\r\n");
      out.write("            <p>Check out the features:</p>\r\n");
      out.write("            <button onclick=\"window.location.href='BrowseItems.jsp'\">Browse Items</button>\r\n");
      out.write("            <button onclick=\"window.location.href='NewAuction.jsp'\">Create New Auction</button>\r\n");
      out.write("            <button onclick=\"window.location.href='view_bids.jsp'\">View Bids</button>\r\n");
      out.write("            <button onclick=\"window.location.href='edit_profile.jsp'\">Edit Profile</button>\r\n");
      out.write("            <button onclick=\"window.location.href='logout.jsp'\">Logout</button>\r\n");
      out.write("            <!-- Add more buttons for additional actions -->\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"additionalButtons\">\r\n");
      out.write("			<button onclick=\"window.location.href='UsersQuestions.jsp'\">Have A Question?</button>   \r\n");
      out.write("			<button onclick=\"window.location.href='Messages.jsp'\">View Messages</button>        \r\n");
      out.write("			<button onclick=\"window.location.href='FAQ.jsp'\">FAQ</button>\r\n");
      out.write("    </main>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2024 BuyMe - All rights reserved</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
